menu: '§l§5§n音乐菜单 ♪~'
open: '§a你打开了音乐菜单！选择一首喜欢的播放吧！'
#——————————
stop: '§4停止播放唱片音乐 ■'
stoplore: 
- '§b如果你播放了上面的唱片音乐'
- '§b你可以通过此选项来关闭'
#——————————
stop2: '§4停止播放背景音乐 ■'
stoplore2: 
- '§b使用此选项，你可以快速'
- '§b关闭游戏背景音乐，包括'
- '§b上面已经开始播放的游戏'
- '§b背景音乐。'
#——————————
m1name: '§e唱片：13'
m1lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m2name: '§e唱片：cat'
m2lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m3name: '§e唱片：blocks'
m3lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m4name: '§e唱片：chirp'
m4lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m5name: '§e唱片：far'
m5lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m6name: '§e唱片：mall'
m6lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m7name: '§e唱片：mellohi'
m7lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m8name: '§e唱片：stal'
m8lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m9name: '§e唱片：strad'
m9lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m10name: '§e唱片：ward'
m10lore:
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m11name: '§e唱片：11'
m11lore: 
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m12name: '§e唱片：wait'
m12lore: 
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m13name: '§e游戏背景音乐：创造'
m13lore: 
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m14name: '§e游戏背景音乐：下界'
m14lore:
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m15name: '§e游戏背景音乐：菜单'
m15lore:
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m16name: '§e游戏背景音乐：末地'
m16lore:
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m17name: '§e游戏背景音乐：特殊'
m17lore:
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————
m18name: '§e游戏背景音乐：生存'
m18lore:
- '§c此选项可多次点击进行切换'
- '§bMinecraft原版音乐'
- '§a点击播放 ▶'
#——————————

